# 文档地址
version: '3.9'
services:
  # 客户端
  client:
    image: IMAGE_TO_SERVER:TAG
    ports:
      - '3000:3000'
      - '9229:9229' # DEBUG
    environment:
      SECRET: session 密钥
      #PINECONE_INDEX:
      #PINECONE_ENVIRONMENT
      #PINECONE_API_KEY
      OPENAI_BASE_PATH: OPENAI 基础路径
      OPENAI_API_KEY: OPENAI 密钥
      BACKEND: http://server:8080
      #NODE_OPTIONS: NODEJS 配置项 # --inspect=0.0.0.0

  # 多人协作服务器
  collab:
    image: wkfe/visual-ddd-collab:latest
    ports:
      - '9090:9090'
    environment:
      MAIN_SERVER: http://client:3000

  # 后端服务
  server:
    image: IMAGE_TO_SERVER:TAG
    ports:
      - '8080:8080'

  # 数据库: TODO
  # redis: TODO

  # https://hub.docker.com/_/nginx
  # nginx 对外负载均衡
  nginx:
    image: 1.23.4-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
