# 用于一些准备工作，比如证书生成
# 启动 docker compose up certbot
version: '3.9'
services:
  # https://hub.docker.com/_/nginx
  # nginx 用于对外验证证书
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./certbot-verify.conf:/etc/nginx/conf.d/default.conf
      # certbot 生成的 HTTP 验证文件
      - ./certbot/www:/usr/share/certbot/www:ro

  # Let's Encrypt 证书生成
  # https://www.cnblogs.com/vishun/p/15746849.html
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      # certbot 生成的 HTTP 验证文件
      - ./certbot/www:/usr/share/certbot/www:rw
      # certbot 生成的证书文件
      - ./certbot/ssl:/etc/letsencrypt:rw
    command: certonly --webroot --webroot-path /usr/share/certbot/www/ -d <%= DOMAIN %> --email <%= EMAIL %> --agree-tos --force-renewal
